### ISSUE TITLE
Api-Key request

### ISSUE THREAD

**Issue by McSlow** [mtb-news/Winterpokal-API#2]
Hi,
ich hab mir gerade gedanken gemacht, wie es möglich wäre, dem user das eintippen des API-Keys zu vereinfachen oder abzunehmen. (z.b. auf mobilen geräten)
Falls ein user auf einem mobilgerät z.b. schon auf mtb-news eingeloggt ist, kann er sich ja ohne weitere Hürden den Apikey auf http://winterpokal.mtb-news.de/api-keys ansehen. Mir ist noch nicht ganz klar ob Browsercookies ( sei es android oder iOS) auch in den Systemgenerischen http-requestemethoden genutzt werden können, wenn ja, wäre es aber möglich -falls der user sich bereits mit cookie auf mtb-news eingeloggt hat- diesen auszulesen. Bis jetzt aber nur obige html-formatierte seite, die wild geparst werden müsste ( mit dem nachteil, das sich bei webdesignänderungen der parser evtl. verhaspelt).

Frage also:
Gibts einen weg bzw. http-request, der die api keys raw oder sogar als json objekt ausgibt ( wenn json, dann natürlich ohne apikey im header nötig _g_). So könnte man dem user tipparbeit ersparen, nicht jeder kennt sich mit copy'n'paste am handy aus und iOS user unter iOSv3 (ok, gut...) ham garkeins.

Gruß,
Bjoern ( McSlow)

**Comment by crolack** [comment]
Das hatte ich auf Rennrad-News auch schon gefragt - ist wohl in Planung. Noch wichtiger ist imho die https-Unterstützung...

Aktuell hole ich mir mit den Userdaten einfach den cookie und damit dann den Api-Key. Also ganz ohne Umweg über den Browser. (Meine App wird übrigens iOS only...)

**Comment by mjaschen** [comment]
Diese Möglichkeit wird eingebaut. Nur leider heute nicht mehr… ;)

**Comment by mjaschen** [comment]
Ich hoffe, dass wir diese Funktion morgen bereit stellen können!

**Comment by mjaschen** [comment]
Die Funktion ist jetzt eingebaut und steht auf mtb-news.de und rennrad-news.de zur Verfügung.

Dokumentation: https://github.com/mtb-news/Winterpokal-API/wiki/API-Funktionen:-Zugriff-auf-API-Keys

**Comment by crolack** [comment]
Hi, 

danke für die schnelle umsetzung.

Wird dabei ein jedes mal ein neuer key erzeugt oder werden nur vorhandene keys ausgegeben?

Dann muss der user ja immer noch per webinterface einen key anlegen? 
Besser wäre, wenn bei der funktion zumindest einen key erzeugt wird, wenn noch keiner vorhanden ist.

Es werde es mir heute abend mal anschauen!

Viele grüße! 

Am 24.11.2011 um 16:42 schrieb "Marcus T. Jaschen"reply@reply.github.com:

**Comment by mjaschen** [comment]
Ich werde es so bauen, dass automatisch ein Token erstellt wird, wenn noch keins vorhanden ist. Ich melde mich dann noch mal hier, sobald es eingebaut ist.

**Comment by mjaschen** [comment]
Es wird jetzt automatisch das erste Token erstellt wenn die Token-Liste per API-Request abgerufen wird und sie noch leer ist.

**Comment by mjaschen** [comment]
Achso, noch zu deiner eigentlichen Frage: Es werden nicht jedes Mal neue Keys erzeugt. Ein Key ist persistent solange bis er vom User gelöscht oder von uns deaktiviert wird.

**Comment by crolack** [comment]
Super!

Ich traue mich zwar kaum noch, weiter zu fragen, aber gerade so lange noch kein https unterstützt wird, macht es sinn, wenigstens das pw als hash mit nem starken salt zu übertragen.

Dann kann das zwar immer noch abgefangen werden, aber der schaden würde sich auf den winterpokal begrenzen. (viele werden ja das gleiche pw überall verwenden...)

Am 24.11.2011 um 17:06 schrieb "Marcus T. Jaschen"reply@reply.github.com:

**Comment by mjaschen** [comment]
HTTPS ist bei mtb-news.de bereits unterstützt, es reicht, den Protocol-Identifier in der URL durch https:// zu ersetzen. Für rennrad-news.de müssen wir erst noch ein Wildcard-Zertifikat kaufen, das sollte aber auch in den nächsten Tagen geschehen.

**Comment by crolack** [comment]
Oh, sehr schön! 

Am 24.11.2011 um 17:17 schrieb "Marcus T. Jaschen"reply@reply.github.com:

**Comment by mjaschen** [comment]
HTTPS geht jetzt auch für winterpokal.rennrad-news.de!

**Comment by crolack** [comment]
HTTPS und bestehenden Api-Key abrufen funktioniert wunderbar! :)
