### ISSUE TITLE
RR-News: Tokens lassen sich nicht mehr abrufen

### ISSUE THREAD

**Issue by crolack** [mtb-news/Winterpokal-API#4]
Hi,

ich habe eben festgestellt, dass sich die Tokens bei RR-News nicht mehr abrufen lassen, bei MTB-News hingegen schon. Da ist wohl beim Umzug etwas kaputt gegangen?

Ich habe nichts an meinem Code geändert und für beides wird bis auf eine andere URL der selbe Code verwendet.

Wenn ich bei RR-News keine Benutzerdaten angebe, bekomme ich eine korrekte Fehlermeldung:

{"status":"ERROR","messages":{"69":"Missing credentials"},"data":null}

Wenn ich richtige oder falsche Daten angebe, bekomme ich gar keine Daten zurück. Bei MTB-News klappt es aber.

Die anderen Api-Funktionen funktionieren sowohl bei MTB-News als auch bei RR-News.

Hier mal der Antwort-Header zum Vergleich. Bei RR-News steht zwar einen Content-Length von 20, aber bei mir kommt gar nichts an.

MTB-News:
2011-12-19 20:49:52.120 Winterpokal[9489:fb03] response: {
    Connection = "keep-alive";
    "Content-Length" = 247;
    "Content-Type" = "application/json; charset=UTF-8";
    Date = "Mon, 19 Dec 2011 19:49:52 GMT";
    Server = "nginx/0.8.54";
    "X-Powered-By" = "PHP/5.3.5-1ubuntu7.2";
    "X-SRV" = newton;
}

RR-News:
2011-12-19 20:50:11.146 Winterpokal[9489:fb03] response: {
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Length" = 20;
    "Content-Type" = "text/html";
    Date = "Mon, 19 Dec 2011 19:50:11 GMT";
    Server = "nginx/0.8.54";
    Vary = "Accept-Encoding";
    "X-Powered-By" = "PHP/5.3.5-1ubuntu7.2";
    "X-SRV" = newton;
}

**Comment by crolack** [comment]
Was ich noch vergessen hatte: Status-Code ist 500.

**Comment by mjaschen** [comment]
Es sollte jetzt funktionieren, bitte teste noch mal!

**Comment by crolack** [comment]
Funktioniert wieder einwandfrei, danke! :)
