### ISSUE TITLE
Testserver vorhanden?

### ISSUE THREAD

**Issue by hgoebl** [mtb-news/Winterpokal-API#8]
Hi, habt ihr einen Testserver mit dem man z.B. auch schon vor dem 30.10. Requests absetzen kann?
(Sorry, falls ich etwas überlesen haben sollte.)

**Comment by mjaschen** [comment]
Hi,

sorry, habe den Eintrag hier übersehen.

Ein Testserver ist das ganze Jahr unter http://winterpokal-apitest.mtb-news.de/ erreichbar (aber nur mit MTB-News.de-Account nutzbar)

Viele Grüße

Marcus

**Comment by hgoebl** [comment]
Super. Vielen Dank. 👍
